spring:
  config:
    import: configserver:http://localhost:8085
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082
